additionalArguments:
  - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  - --certificatesresolvers.cloudflare.acme.dnschallenge=true
  - --certificatesResolvers.cloudflare.acme.dnsChallenge.delayBeforeCheck=0
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=howdy.rvtr@outlook.com
  - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
  - --metrics=true
  - --metrics.prometheus=true
  - --metrics.prometheus.entryPoint=traefik
  - --tracing=true
  - --tracing.zipkin=true
  - --tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans

affinity: {}

autoscaling:
  enabled: false

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}

env: []

envFrom:
  - secretRef:
      name: rvtr-dns

globalArguments:
  - '--global.checknewversion'
  - '--global.sendanonymoususage'

hostNetwork: false

image:
  name: traefik
  tag: 2.2.1

ingressRoute:
  dashboard:
    enabled: false
    annotations: {}
    labels: {}

nodeSelector: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {}

podSecurityContext:
  fsGroup: 65532

ports:
  analytics:
    port: 3000
    expose: true
    exposedPort: 3000
  http:
    port: 8000
    expose: true
    exposedPort: 80
  https:
    port: 8443
    expose: true
    exposedPort: 443
  metrics:
    port: 9090
    expose: true
    exposedPort: 9090
  tracing:
    port: 9411
    expose: true
    exposedPort: 9411
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
  web: null
  websecure: null

priorityClassName: ''

resources: {}

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

tolerations: []

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  spec:
    loadBalancerIP: ''
  loadBalancerSourceRanges: []
  externalIPs: []

serviceAccountAnnotations: {}

volumes: []
