---
apiVersion: v1
data:
  users: YWRtaW46JDJ5JDA1JHVBVVdLQi8zVVNqM1hORzd3SWp3RHVNZVBYekdxVUkua2pUeTc3Ljg1UnZJRTVMRWM3MDdhCg==
kind: Secret
metadata:
  name: rvtr-auth
type: Opaque

---
apiVersion: v1
data:
  CF_DNS_API_TOKEN: Z3dHWUNsOE1OOHNMVzZJc3JjMWJob0pfREc0TUNGakJHUWZ3anZtcw==
kind: Secret
metadata:
  name: rvtr-dns
type: Opaque
