---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kernel
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kernel
    spec:
      containers:
        - image: grafana/grafana
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana-http

        - image: prom/prometheus
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: prometheus
          ports:
            - containerPort: 9090
              name: prometheus-http
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/

        - image: openzipkin/zipkin-slim
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: zipkin
          ports:
            - containerPort: 9411
              name: zipkin-http

      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Release.Name }}-prometheus
