---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kernel
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kernel
    spec:
      containers:
        - env:
            {{- with .Values.variables.grafana }}
            - name: GF_AUTH_PROXY_AUTO_SIGN_UP
              value: {{ .proxyAutoSignUp }}
            - name: GF_AUTH_PROXY_ENABLED
              value: {{ .proxyEnabled }}
            - name: GF_AUTH_PROXY_HEADER_NAME
              value: {{ .proxyHeaderName }}
            - name: GF_AUTH_PROXY_HEADER_PROPERTY
              value: {{ .proxyHeaderProperty }}
            {{- end }}
          image: grafana/grafana
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana-http
          resources:
            limits:
              cpu: '250m'
              memory: '128Mi'

        - env:
            {{- with .Values.variables.idaas }}
            - name: IDAAS__ClientId
              value: {{ .clientId }}
            - name: IDAAS__Provider
              value: {{ .provider }}
            - name: IDAAS__RedirectUri
              value: {{ .redirectUri }}
            {{- end }}
          image: rvtr/traefik-idaas
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: idaas
          ports:
            - containerPort: 80
              name: idaas-http
          resources:
            limits:
              cpu: '250m'
              memory: '128Mi'

        - image: prom/prometheus
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: prometheus
          ports:
            - containerPort: 9090
              name: prometheus-http
          resources:
            limits:
              cpu: '250m'
              memory: '128Mi'
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/

        - image: openzipkin/zipkin-slim
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: zipkin
          ports:
            - containerPort: 9411
              name: zipkin-http
          resources:
            limits:
              cpu: '250m'
              memory: '256Mi'

      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Release.Name }}-prometheus
