---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana-http
  selector:
    app: {{ .Release.Name }}-kernel
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  ports:
    - name: prometheus
      port: 9090
      targetPort: prometheus-http
  selector:
    app: {{ .Release.Name }}-kernel
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zipkin
spec:
  ports:
    - name: zipkin
      port: 9411
      targetPort: zipkin-http
  selector:
    app: {{ .Release.Name }}-kernel
  type: {{ .Values.service.type }}
