jobs:
  validate:
    defaults:
      run:
        working-directory: hashicorp
    name: validate_terraform
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.2.0
      - name: terraform_setup
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_version: 0.12.26
      - name: terraform_init
        run: terraform init --backend=false
      - name: terraform_validate
        run: terraform validate

name: build

on:
  pull_request:
    branches:
      - master
