jobs:
  plan:
    defaults:
      run:
        working-directory: hashicorp
    env:
      TF_WORKSPACE: azure
    name: plan_terraform
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.2.0
      - name: terraform_setup
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.12.26
      - name: terraform_init
        run: terraform init --backend-config=backend.hcl
      - name: terraform_validate
        run: terraform validate
      - name: terraform_plan
        run: terraform plan

name: release

on:
  push:
    branches:
      - master
    tags:
      - '*'
