jobs:
  build:
    defaults:
      run:
        working-directory: hashicorp
    name: build_terraform
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.2.0
      - name: terraform_init
        run: terraform init
      - name: terraform_validate
        run: terraform validate

name: release

on:
  push:
    branches:
      - master
    tags:
      - '*'
